#! /bin/bash

# Monitoring

kubectl apply -f monitoring/namespace.yml
helm install stable/prometheus \
    --namespace monitoring \
    --name prometheus \
    -f prometheus/values.yml

kubectl apply -f monitoring/grafana/config.yml
helm install stable/grafana \
    -f monitoring/grafana/values.yml \
    --set persistence.enabled=true --set persistence.accessModes={ReadWriteOnce} --set persistence.size=8Gi \
    --namespace monitoring \
    --name grafana

kubectl get secret \
    --namespace monitoring \
    grafana \
    -o jsonpath="{.data.admin-password}" \
    | base64 --decode ; echo
